#+LATEX_CLASS: article
#+DATE: 2015-04-27
#+TITLE: Penalty Shot SfN 2015
#+OPTIONS: toc:nil author:nil date:nil ^:{}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \setlength{\droptitle}{-1.5cm}
#+LATEX_HEADER: \posttitle{\par\end{center}\vspace{-1cm}}
#+LATEX_HEADER: \setlength{\parindent}{0cm}
#+LATEX_HEADER: \usepackage[margin=2cm]{geometry} \usepackage{svg}
#+KEYWORDS: [+PenaltyKik, +PenaltyShot, +Abstract, +Presentation, +SfN2015]

* Abstract
  #+AUTHOR: William F. Broderick, R. McKell Carter, Mariano Tepper, Jean-François Gariépy, Michael L. Platt, Guillermo Sapiro, Scott A. Huettel

  Theme-subtheme-subject: F.01.p.

  Cognition and Behavior -- Human Cognition and Behavior -- Decision making and reasoning

** A multi-variate pattern analysis investigation of strategic thinking and deception in a dynamic, competitive game.

   Successful human interactions depend upon the interpretation of an
   agent's behaviors and intentions in order to support strategic control
   of the agent's behaviors and decisions. Interpreting others' actions
   requires many elements of social cognition, including more complex
   functions like theory of mind. Although there is some consistency in
   the neural substrates identified as supporting these functions
   (e.g. the medial-prefrontal cortex and temporal-parietal junction,
   TPJ), most tasks employ static or sequential interactions that do not
   allow investigation of differing levels of social-cognitive engagement
   on a short time scale. In this study, we adapted a dynamic,
   competitive game modeled on a simplified penalty kick, wherein humans
   ($N=29$) controlled a ball, attempting to score against a human- or
   computer-controlled goalie, while measures of brain activation were
   obtained using functional magnetic resonance imaging (fMRI). This
   allowed us to quantitatively characterize subjects' strategic
   interactions with their opponent -- and how these strategies change
   over short and longer time scales. K-means clustering on the
   difference between the y position of the subject-controlled ball and
   human-controlled goalie revealed that participant behavior reduced to
   two clusters, one pair representing early feints and misdirections
   (i.e., separation between participant and opponent near the start of
   the trial) and the other representing strategies intended to hide the
   kicker's intention for as long as possible (i.e., separation only at
   the end of the trial). These clusters -- each further separable into
   pairs of upward or downward movements -- correspond to distinct
   behavioral strategies. Play against a computer opponent served as a
   non-social baseline with similar strategic interactions. Using
   multivariate pattern analysis (MVPA), we examined whether local brain
   regions carried information that predicted trial features (e.g.,
   opponent, outcome, strategy). Confirmatory analyses found that visual
   regions can be used to classify human from computer opponents at the
   time the opponent is revealed. MVPA of strategic interaction focused
   on the neural response differences between the two strategy-defined
   clusters. Using this dynamic task allows distinction of strategic
   elements of deception (e.g., timing of movement) from the conditions
   that elicit deception, the nature of the opponent, and the outcome of
   the action. The use of dynamic tasks facilitates the study of
   strategic social interaction on short timescales, opening avenues for
   causal studies of the supporting neural substrates.

* Poster notes

  Want to start with some sort of intro to deceptive behavior, mention
  that deceptive behavior is typically online and dynamic whereas lots
  of studies are static, talk a bit about the monkey study, then move
  into our stuff.

  
