#+LATEX_CLASS: article
#+DATE: 2015-04-27
#+TITLE: Penalty Shot SfN 2015
#+OPTIONS: toc:nil author:nil date:nil ^:{}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \setlength{\droptitle}{-1.5cm}
#+LATEX_HEADER: \posttitle{\par\end{center}\vspace{-1cm}}
#+LATEX_HEADER: \setlength{\parindent}{0cm}
#+LATEX_HEADER: \usepackage[margin=2cm]{geometry} \usepackage{svg}
#+KEYWORDS: [+PenaltyKik, +PenaltyShot, +Abstract, +Presentation, +SfN2015]

* Abstract
  #+AUTHOR: William F. Broderick, R. McKell Carter, Mariano Tepper, Jean-François Gariépy, Michael L. Platt, Guillermo Sapiro, Scott A. Huettel

  Theme-subtheme-subject: F.01.p.

  Cognition and Behavior -- Human Cognition and Behavior -- Decision making and reasoning

** A multi-variate pattern analysis investigation of strategic thinking and deception in a dynamic, competitive game.

   Successful human interactions depend upon the interpretation of an
   agent's behaviors and intentions in order to support strategic control
   of the agent's behaviors and decisions. Interpreting others' actions
   requires many elements of social cognition, including more complex
   functions like theory of mind. Although there is some consistency in
   the neural substrates identified as supporting these functions
   (e.g. the medial-prefrontal cortex and temporal-parietal junction,
   TPJ), most tasks employ static or sequential interactions that do not
   allow investigation of differing levels of social-cognitive engagement
   on a short time scale. In this study, we adapted a dynamic,
   competitive game modeled on a simplified penalty kick, wherein humans
   ($N=29$) controlled a ball, attempting to score against a human- or
   computer-controlled goalie, while measures of brain activation were
   obtained using functional magnetic resonance imaging (fMRI). This
   allowed us to quantitatively characterize subjects' strategic
   interactions with their opponent -- and how these strategies change
   over short and longer time scales. K-means clustering on the
   difference between the y position of the subject-controlled ball and
   human-controlled goalie revealed that participant behavior reduced to
   two clusters, one pair representing early feints and misdirections
   (i.e., separation between participant and opponent near the start of
   the trial) and the other representing strategies intended to hide the
   kicker's intention for as long as possible (i.e., separation only at
   the end of the trial). These clusters -- each further separable into
   pairs of upward or downward movements -- correspond to distinct
   behavioral strategies. Play against a computer opponent served as a
   non-social baseline with similar strategic interactions. Using
   multivariate pattern analysis (MVPA), we examined whether local brain
   regions carried information that predicted trial features (e.g.,
   opponent, outcome, strategy). Confirmatory analyses found that visual
   regions can be used to classify human from computer opponents at the
   time the opponent is revealed. MVPA of strategic interaction focused
   on the neural response differences between the two strategy-defined
   clusters. Using this dynamic task allows distinction of strategic
   elements of deception (e.g., timing of movement) from the conditions
   that elicit deception, the nature of the opponent, and the outcome of
   the action. The use of dynamic tasks facilitates the study of
   strategic social interaction on short timescales, opening avenues for
   causal studies of the supporting neural substrates.

* Poster notes

  Want to start with some sort of intro to deceptive behavior, mention
  that deceptive behavior is typically online and dynamic whereas lots
  of studies are static, talk a bit about the monkey study, then move
  into our stuff.

  From McKell, in reference to commit [[https://github.com/billbrod/SfN.2015/commit/18c63e0c7d7f1125d357a273b8b2d8351fdba04f][18c63e0]]: titles are a bit long
  and should focus on what should be taken away, not details. Can add
  details in bullets below. Someone should be able to just read the
  titles and understand what I want them to take away. For this, write
  my main question and what answer I want them to leave with (should
  be how or why not yes/no). Would be good to have preliminary data
  from JF or Caroline in that first column: why is this task good,
  what does it tell us that others don't? What does human data bring
  to the equation? What are our goals? Then can shrink those two big
  screen pics and move to the second column (have movie example of
  trial on tablet). Describe the planned imaging analyses and can
  maybe add a few things last minute. Put references in bottom right
  corner.

  - [X] Write main question and answer down, use as frame
  - [X] Rework titles
  - [X] Add bullet points
  - [X] Get preliminary data from JF or Caroline in first column
  - [X] Why this task? What does human data bring? What are our goals?
  - [X] Shrink and move screen pics to second column
  - [ ] Put movie example on tablet
  - [X] Describe imaging analysis
    - [X] Create image summarizing MVPA searchlight regression (see
      McKell's poster for inspiration, use [[https://www.csie.ntu.edu.tw/~cjlin/libsvm/index.html?js=1#svm-toy-js][LibSVM]] applet to generate
      example regression)
    - [X] Create image summarizing Stelzer et al's cluster method (see
      their figures 1 and 2, but those are very text heavy
  - [X] Check if players using mixed-strategy outperform those who use
    only one -- doesn't quite look like that, sent note to McKell to
    see what he thinks


  Main question: How do humans use deception to attempt to beat their
  opponents in a competitive, dynamic game?

  Answer: They use a mixture of two strategies, early and late
  deception, in an attempt to both deceive and be unpredictable. 

  To make this more interesting, looking at trial-to-trial
  dependencies (correlation on metric between trials and metric over
  time) would help, as well as showing there's no difference in
  win/loss percentages. Could also include figure showing metric
  vs. computer; include distribution?

  For monkey stuff: all their figures are either mutual information
  (which we can't use) or neuronal recordings. What are their points?
  That monkeys much less predictable against live opponents, use
  pre-planned feints (neurons in DLPFC) to attempt to deceive
  opponents. Inhibiting those neurons makes them much more
  predictable. Additionally, eye gaze prior to trial onset much more
  predictable than position until very close to end. So this shows us
  that there are neuronal correlates of planned deception.

  Why this task? Dynamic, allows us to investigate deception online,
  more like real-world situation where agents are reacting to each
  other, in contrast to many other tasks where deception is static or
  sequential. 

  What does human data bring? Humans appear to use more deception, in
  more intentional ways than other primates (?), our data shows that
  the manner in which they deceive is very different (go back much
  more often, movements are not nearly as pre-planned)

  What are our goals? To see how similar humans are to monkeys, how
  participants use deception to attempt to beat their opponents in a
  competitive game.

  
